import Link from "next/link";
import { notFound } from "next/navigation";
import { ApiError, getCorpusClaim } from "@/app/lib/api";

export default async function ClaimPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  let claim;
  try { claim = await getCorpusClaim(id); } catch (error) { if (error instanceof ApiError && error.status === 404) notFound(); throw error; }
  return <div className="mx-auto max-w-4xl px-5 py-10"><Link href={`/papers/${claim.paper_id}`} className="text-sm text-tide-700">← Papier</Link><p className="mt-6 font-mono text-sm text-ink-400">{claim.field_path}</p><h1 className="mt-2 font-display text-3xl">Information {claim.claim_id}</h1><div className="mt-5 rounded-2xl border border-rule bg-white p-6"><p className="text-xl">{typeof claim.value === "string" ? claim.value : JSON.stringify(claim.value)} {claim.unit}</p><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-[10rem_1fr]"><dt>Vérification</dt><dd>{claim.verification_state}</dd><dt>Provenance</dt><dd>{claim.claim_type}</dd><dt>Expérience</dt><dd>{claim.experiment_id || "—"}</dd><dt>Édition déclarée</dt><dd>{claim.evidence.source_edition || "—"}</dd><dt>Locator du classeur</dt><dd>{[claim.evidence.pdf_page ? `p. ${claim.evidence.pdf_page}` : null, claim.evidence.section, claim.evidence.locator].filter(Boolean).join(" · ") || "—"}</dd><dt>Extrait du classeur</dt><dd>{claim.evidence.verbatim_evidence || "Aucun extrait verbatim fourni."}</dd></dl></div><section className="mt-8"><h2 className="font-display text-2xl">Historique d’audit</h2>{claim.audits?.length ? <ol className="mt-3 space-y-3">{claim.audits.map((audit) => <li key={audit.event_id} className="rounded-xl border border-rule bg-white p-4"><strong>{audit.decision}</strong> · {audit.auditor_id} · {audit.audited_at}{audit.current === false && <strong className="ml-2 text-red-700">Décision périmée : la ligne a changé</strong>}<p className="mt-2 text-sm text-ink-600">{audit.justification}</p><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-[8rem_1fr]"><dt>Source auditée</dt><dd>{audit.source_kind} · {audit.source_edition}</dd><dt>Locator</dt><dd>{[audit.page ? `p. ${audit.page}` : null, audit.section, audit.locator].filter(Boolean).join(" · ") || "—"}</dd><dt>Preuve d’audit</dt><dd>{audit.evidence || "—"}</dd></dl></li>)}</ol> : <p className="mt-3 text-ink-500">Aucune décision d’audit indépendante enregistrée.</p>}</section></div>;
}
